repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^question-generator/apps/api/
      - id: end-of-file-fixer
        files: ^question-generator/apps/api/
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        files: ^question-generator/apps/api/
      - id: ruff-format
        files: ^question-generator/apps/api/

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: ^question-generator/apps/api/
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^question-generator/apps/api/
        args: ["--config-file", "question-generator/apps/api/pyproject.toml"]